In [2]:
from elasticsearch import Elasticsearch
import pandas as pd
import sqlite3
from datetime import datetime, timezone
from IPython.display import display, HTML
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
from sentence_transformers import SentenceTransformer, util
from tqdm.notebook import tqdm

import numpy as np

import time
import json
import re

model = SentenceTransformer('all-MiniLM-L6-v2')

db_path = '/Users/zphilipp/git/research/dealsdb/deals_db1.db'
index_name = 'deals' 
    
words_to_remove = [
    "about", "above", "across", "after", "against", "along", "among", "around", 
    "before", "behind", "below", "beneath", "beside", "between", "beyond", "by",
    "during", "for", "from", "in", "inside", "into", "near", "of", "off", "on",
    "out", "outside", "over", "through", "throughout", "toward", "under",
    "until", "within", "without", "and", "but", "or", "for", "nor",
    "so", "yet", "although", "because", "as", "since", "unless", "while", "when",
    "where", "after", "before", "the", "a", "b", "c", "d", "e", "f", "g", "h",
    "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u",
    "v", "w", "x", "y", "z", "aa", "aaa", "aaaa", #, "to", "up", "with", "at",
]

words_pattern = r'\b(' + '|'.join(map(re.escape, words_to_remove)) + r')\b'

def remove_prepositions_and_conjunctions(text):
    text = remove_chinese_characters(text).lower()
    cleaned_text = re.sub(words_pattern, '', text, flags=re.IGNORECASE)
    cleaned_text = re.sub(r"[();,'\\\[\]0-9]+", "", cleaned_text) # special charch and one place numbers
    return re.sub(r'\s+', ' ', cleaned_text).strip()

def remove_chinese_characters(text):
    # Regular expression pattern to match Chinese characters
    patt = r'[\u4e00-\u9fff]+'
    # Substitute Chinese characters with an empty string
    cleaned_text = re.sub(patt, '', text)
    return cleaned_text
    
sql_query = """
        SELECT                                 
            d.id,
            
            COALESCE(MAX(d.title_general), '') || ' ' ||
            COALESCE(GROUP_CONCAT(o.title, ','), '') || ' ' ||
            COALESCE(MAX(m.name), '') AS text,
            
            d.customer_category_id
        FROM deals d
            LEFT JOIN merchant m ON (d.merchant_id=m.id)
            LEFT JOIN options o ON (o.deal_id=d.id)
        -- where d.id=151
        GROUP BY d.id
"""

def remove_prepositions_and_conjunctions(text):
    text = remove_chinese_characters(text).lower()
    cleaned_text = re.sub(words_pattern, '', text, flags=re.IGNORECASE)
    cleaned_text = re.sub(r"[();,'\\\[\]0-9]+", "", cleaned_text) # special charch and one place numbers
    return re.sub(r'\s+', ' ', cleaned_text).strip()

def remove_chinese_characters(text):
    # Regular expression pattern to match Chinese characters
    patt = r'[\u4e00-\u9fff]+'
    # Substitute Chinese characters with an empty string
    cleaned_text = re.sub(patt, '', text)
    return cleaned_text

#def get_important_words(document):
    #document = remove_prepositions_and_conjunctions(document)
    #document = [document]

    #vectorizer = TfidfVectorizer(ngram_range=(1, 3))
    #tfidf_matrix = vectorizer.fit_transform(document)

    #feature_names = vectorizer.get_feature_names_out()
    #first_document_vector = tfidf_matrix[0]
    
#    important_words = sorted(
#        [(feature_names[i], first_document_vector[0, i]) for i in first_document_vector.nonzero()[1]],
#        key=lambda x: x[1], reverse=True
#    )
#    return important_words


    

def to_dict(important_words):
    result_dict = {
        'unigram': [],
        'bigram': [],
        'trigram': []
    }
    for word, weight in important_words:
        if weight < 0.03:
            continue
        #print (word, weight)
        word = word.encode().decode('unicode_escape')
        word_count = len(word.split())

        if word_count == 1:
            result_dict['unigram'].append((word, weight))
        elif word_count == 2:
            result_dict['bigram'].append((word, weight))
        elif word_count == 3:
            result_dict['trigram'].append((word, weight))
    return json.dumps(result_dict)

/Users/zphilipp/miniconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [2]:
es = Elasticsearch(
    ['https://localhost:9200'],
    basic_auth=('elastic', 'M=kZVPINr+3A7GtTEpMx'),
    ca_certs='/Users/zphilipp/http_ca.crt'
)

In [3]:
es.info()

ObjectApiResponse({'name': '57d81a9748d2', 'cluster_name': 'docker-cluster', 'cluster_uuid': '6aUsePzoRouhWmwyyrJvdQ', 'version': {'number': '8.17.2', 'build_flavor': 'default', 'build_type': 'docker', 'build_hash': '747663ddda3421467150de0e4301e8d4bc636b0c', 'build_date': '2025-02-05T22:10:57.067596412Z', 'build_snapshot': False, 'lucene_version': '9.12.0', 'minimum_wire_compatibility_version': '7.17.0', 'minimum_index_compatibility_version': '7.0.0'}, 'tagline': 'You Know, for Search'})

In [4]:
if es.indices.exists(index=index_name):
    es.indices.delete(index=index_name)
else:
    pass
    
index_settings = {
    'settings': {
        'number_of_shards': 1,
        'number_of_replicas': 1,
    },
    'mappings': {
        'properties': {
            #'id': {'type': 'integer'},
            'deal_uuid': {'type': 'text'},
            'document': {'type': 'text'},
            'category': {'type': 'text'},
            'timestamp': {'type': 'date'},
        }
    }
}
es.indices.create(index=index_name, body=index_settings)
#
# "properties": {
#      "vector": {
#        "type": "dense_vector",
#        "dims": 128
#      }
#    }

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': True, 'index': 'deals'})

In [5]:
index_info = es.indices.get(index=index_name)
index_mapping = index_info[index_name]['mappings']
mapping_df = pd.json_normalize(index_mapping['properties'])
mapping_df

search_query = {
  "size": 0
}
response = es.search(index=index_name, body=search_query)
response

ObjectApiResponse({'took': 3, 'timed_out': False, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}, 'hits': {'total': {'value': 0, 'relation': 'eq'}, 'max_score': None, 'hits': []}})

In [5]:
def fetch_tree(item_id, cursor):
    """Funkce pro načtení stromu pro daný item_id."""
    # Načtěte vlastnosti aktuální položky
    cursor.execute("SELECT parent_id, name FROM category WHERE id = ?", (item_id,))
    item = cursor.fetchone()
    #print(item)
    if not item:
        return None
    
    # Vytvoření uzlu
    return {
        'value': item[1],
        'parent_id': item[0]
    }

def get_taxonomy_path(id, cursor):

    data = fetch_tree(id, cursor)
    category_string = ""
    while data is not None:    
        data = fetch_tree(data["parent_id"], cursor)
        try:
            category_string = data["value"] + " / " + category_string
        except TypeError as e:
            #print (data)
            break
    
    return category_string[:-2]

In [8]:
counter  = 0
counterTotal = 0
errors = 0

conn = sqlite3.connect(db_path)
cursor = conn.cursor()
sql_query = """
        SELECT                                 
            d.deal_uuid,
            
            COALESCE(MAX(d.title_general), '') || '. ' ||
            COALESCE(MAX(d.highlights), '') || '. ' ||
            COALESCE(GROUP_CONCAT(o.title, ','), '') || '. ' ||
            COALESCE(MAX(m.name), '') AS text,
            
            d.customer_category_id
        FROM deals d
            LEFT JOIN merchant m ON (d.merchant_id=m.id)
            LEFT JOIN options o ON (o.deal_id=d.id)
        -- where d.id=151
        GROUP BY d.deal_uuid
    """
cursor.execute(sql_query)

rows = cursor.fetchall()
with tqdm(total=len(rows)) as pbar:
    for row in rows:

        # index when deal have category only
        if row[2]:
            try:

                #print (f"Row 1: {row[1]}")
                category = get_taxonomy_path(row[2], cursor)
                document = row[1].encode().decode('unicode_escape')
                document = remove_prepositions_and_conjunctions(document + '. ' + category.strip() + '.')

                body = {
                    #'id': row[0],
                    'deal_uuid' : row[0],
                    'document': document,
                    'category' : category,
                    'timestamp': datetime.now(timezone.utc).isoformat()
                }    
                #print (body)
                #break

                es.index(index=index_name, body=body)
            except Exception as e:
                print (f"Exception.: {e} Row 1 {row[1]}.")
                print (f"Error in document id.: {row[0]}.")
                print (f"Body: {body}.")
                errors = errors + 1
                raise
            
            counter = counter + 1
        counterTotal = counterTotal + 1
        pbar.update(1)
    
    conn.close()
    print (f"Errors: {errors}.")
    print (f"Total feeds: {counterTotal}.")
    print (f"Indexed feeds: {counter}.")
    print (f"Deals without category: {counterTotal - counter}.")

  0%|          | 0/105789 [00:00<?, ?it/s]

/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_12182/1007185202.py:35: DeprecationWarning: invalid escape sequence '\S'
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_12182/1007185202.py:35: DeprecationWarning: invalid escape sequence '\A'
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_12182/1007185202.py:35: DeprecationWarning: invalid escape sequence '\o'
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_12182/1007185202.py:35: DeprecationWarning: invalid escape sequence '\ '
  document = row[1].encode().decode('unicode_escape')

Errors: 0.
Total feeds: 105789.
Indexed feeds: 93044.
Deals without category: 12745.

In [22]:
#search_term = 'oil change'
pd.set_option('display.max_colwidth', 10)
#search_term = 'Oil changes change Engine replacement services Lubr ication filter Routine oil change Motor oil change Oil maintenance Oil service intervals'
#query_vector = model.encode(search_term).tolist()
search_term = "massage"
#query_vector = model.encode(search_term).tolist()

#search_term = 'val'
start_time = time.time()

search_query = {
    "_source": ["deal_uuid", "document", "category"],
    "size": 10,
    "query": {
        "function_score": {
            "query": {
                "match": {
                    "document": {
                        "query": search_term,  # Ujistěte se, že search_term je definováno
                        "boost": 1
                    }
                }
            },
            "boost_mode": "sum"  # Zajištění, že vražené skóre je použito
        }
    }
}

response = es.search(index=index_name, body=search_query)
end_time = time.time()
elapsed_time = end_time - start_time
#print (response)
documents = []
for hit in response['hits']['hits']:
    document = hit['_source']
    score = hit['_score']

    document['score'] = score
    documents.append(document)

df = pd.DataFrame(documents)
df['document'] = df.apply(lambda x: f'<a href="https://www.groupon.com/deals/{x["deal_uuid"]}" target="_blank">{x["document"]}</a>', axis=1)

display(HTML("<strong>Retrieval: " + str(df['deal_uuid'].count()) + f" deals. In {elapsed_time:.6f}" + "s.</strong>"))
display(HTML(df[["deal_uuid", "document", "category", "score"]].head(1000).to_html(escape=False)))

### search in categories

In [13]:
query = 'Mattresses'

search_query = {
    'query': {
        'multi_match': {
            'query': query,
            'fields': ['category']
        }
    },
    'size': 10000
}

response = es.search(index=index_name, body=search_query)
documents = []
for hit in response['hits']['hits']:
    document = hit['_source']
    score = hit['_score']
    document['score'] = score
    documents.append(document)
    
df = pd.DataFrame(documents)
df['title'] = df.apply(lambda x: f'<a href="https://www.groupon.com/deals/{x["deal_id"]}" target="_blank">{x["title_general"]}</a>', axis=1)
print(df.count())
display(HTML(df[["title_general", "category", "score"]].head(100).to_html(escape=False)))

deal_id          1
title_general    1
option_titles    1
category         1
timestamp        1
score            1
title            1
dtype: int64

### Deals Embedings

In [6]:
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

sql_query = """DROP TABLE IF EXISTS embedings"""
cursor.execute(sql_query)
sql_query = """CREATE TABLE embedings (deal_id TEXT, embedings TEXT)"""
cursor.execute(sql_query)

conn.commit()

sql_query = """
        SELECT                                 
            d.deal_uuid,
            
            COALESCE(MAX(d.title_general), '') || '. ' ||
            COALESCE(GROUP_CONCAT(o.title, ','), '') || '. ' ||
            COALESCE(MAX(m.name), '') AS text,
            
            d.customer_category_id
        FROM deals d
            LEFT JOIN merchant m ON (d.merchant_id=m.id)
            LEFT JOIN options o ON (o.deal_id=d.id)
        -- where d.id=151
        GROUP BY d.id
    """
cursor.execute(sql_query)

rows = cursor.fetchall()
with tqdm(total=len(rows)) as pbar:
    for row in rows:
        category = ''
        if row[2]:
            category = get_taxonomy_path(row[2], cursor)
        document = row[1].encode().decode('unicode_escape')
        document = remove_prepositions_and_conjunctions(document + '. ' + category.strip() + '.')

        emb = model.encode(document).tolist()
        emb = json.dumps(emb)
        sql_query = """INSERT INTO embedings (deal_id, embedings) VALUES (?, ?)"""
        cursor.execute(sql_query, (row[0], emb))
        conn.commit()
        pbar.update(1)

conn.close()

  0%|          | 0/105789 [00:00<?, ?it/s]

/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_66298/2727384824.py:34: DeprecationWarning: invalid escape sequence '\A'
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_66298/2727384824.py:34: DeprecationWarning: invalid escape sequence '\ '
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_66298/2727384824.py:34: DeprecationWarning: invalid escape sequence '\o'
  document = row[1].encode().decode('unicode_escape')
/var/folders/r0/dzfjhfp97r16q08y_8sxyg9m0000gp/T/ipykernel_66298/2727384824.py:34: DeprecationWarning: invalid escape sequence '\S'
  document = row[1].encode().decode('unicode_escape')